
---
- name: Install Glances 
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  
  tasks:

  - name: install => pip3 [CentOS-RHEL]
    yum:
     name: python3-pip
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'    

  - name: install => pip3 [Ubuntu-Debian]
    apt:
     name: python3-pip
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'    
    
  - name: install => glances
    pip:
     name: glances[all]
     executable: pip3.3
