
---
- name: Install Glances 
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  
  tasks:

  - name: install => pip3 + gcc + python-devel [CentOS-RHEL]
    yum:
     name: 
     - python3-pip
     - gcc
     - python-devel
     - python3-devel
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'    

  - name: install => pip3 [Ubuntu-Debian]
    apt:
     name: python3-pip
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'    
    
  - name: install => glances
    pip:
     name: glances[all]
     executable: pip3

  - name: copy => glancesweb.service
    template:
     src: glancesweb.service
     dest: "/usr/lib/systemd/system/glancesweb.service"
     mode: u=rw,g=r,o=
     owner: root

  - name: systemd => daemon-reload
    systemd:
     daemon_reload: yes

  - name: systemd => start glancesweb.service
    systemd:
     name: glancesweb.service
     state: started
