---
- name: Update Servers 
  hosts: "{{ host_name }}"
  become: true
  become_user: root
  become_method: sudo


  tasks:

  - name: upgrade => [CentOS-RHEL]
    yum:
      name: "*"
      state: latest 
    async: 180 # the total time allowed to complete the package update task
    poll: 0 # Polling Interval in Seconds. No need to poll, fire and forget.
    register: yum_update    
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' 

  - name: upgrade  => [Ubuntu-Debian]
    apt:
      upgrade: yes
      update_cache: yes
      force_apt_get: yes 
    async: 180 # the total time allowed to complete the package update task
    poll: 0 # Polling Interval in Seconds. No need to poll, fire and forget.
    register: apt_update
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'    

  - name:  
    debug:
      var: "{{ item }}"
    with_items:
       - yum_update
       - apt_update
    when: debug_mode == true

  - name: check => yum upgrade 
    async_status:
      jid: "{{ yum_update.ansible_job_id }}"
    register: job_result
    until: job_result.finished # Retry within limit until the job status changed to "finished": 1
    retries: 50 # Maximum number of retries to check job status
    delay: 30
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: check => apt upgrade
    async_status:
      jid: "{{ apt_update.ansible_job_id }}"
    register: job_result
    until: job_result.finished # Retry within limit until the job status changed to "finished": 1
    retries: 50 # Maximum number of retries to check job status
    delay: 30
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
